- scripts_data/carga_masiva.py
Se hace merge de script en python para carga masiva y correcciones comentarios.
> se remueven comentarios #19

- .drone.yml
> Integración CI con drone

- Dockerfile
- entrypoint.sh
> Se agrega archivo Dockerfile y entrypoint

- main.go
Se corrigen nombres que no aparecen en las raices del arbol de apr aprobado
> correccion nombres arbol apr aprobado

- controllers/necesidad.go
- helpers/necesidadHelper/necesidad.helper.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
Si la necesidad ya existe, se elimna la necesidad y se vuelve a
registrar con los valores enviados.
Sino existe, simplemente se registra
issue #48
> Actualizando servicio para registrar necesidad

- helpers/necesidadHelper/necesidad.helper.go
- swagger/swagger.json
Se corrigue la forma de obtener la información de una fuente. Agregando la vigencia y unidad ejecutora
issue #48
> actualizando necesidad.helper

- controllers/necesidad.go
- helpers/necesidadHelper/necesidad.helper.go
- swagger/swagger.json
> fixing registrar necesidad tr y getfullnecesidad

- helpers/necesidadHelper/necesidad.helper.go
> Fixing actividad especifica necesdades.helper

- helpers/necesidadHelper/necesidad.helper.go
- swagger/swagger.json
* consecutivo de solicitud
* consecutivo de necesidad
issue #107
> Agregando consecutivos:

- .drone.yml
Se actualiza drone.yml de acuerdo a los nuevos lineamientos
> Se actualiza drone.yml

- .drone.yml
> Se actualiza drone.yml pt 2

- helpers/cdpHelper/cdp.helper.go
- swagger/swagger.json
ajuste expedir cdp y consecutivo provisional
> ajuste expedir cdp y consecutivo provisional

- controllers/modificacion_presupuestal.go
- helpers/cdpHelper/cdp.helper.go
- models/modificacion_presupuestal.go
- swagger/swagger.json
Dev->Test Nov 16 Ajustes modificaciones y mock cdp
> Dev->Test Nov 16 Ajustes modificaciones

- controllers/crp.go
- helpers/crpHelper/crp.helper.go
- models/crp.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
Solicitud de CRPs , expedición de CRPs y consecutivos
> servicios de registros presupuestales

- controllers/necesidad.go
> fix error edicion necesidad

- controllers/necesidad.go
- models/modificacion_presupuestal.go
- swagger/swagger.json
[Issue](https://github.com/udistrital/presupuesto_cliente/issues/156)
> Dev -» Test Nov 25 organiza modificaciones

- helpers/necesidadHelper/necesidad.helper.go
[Issue #107](https://github.com/udistrital/necesidades_cliente/issues/107)
> ajuste devolver arreglos vacios en get full necesidad

- controllers/crp.go
- helpers/crpHelper/crp.helper.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
Servicio de CRP y financiación 
[Issue #161](https://github.com/udistrital/presupuesto_cliente/issues/161)
> Detallecrp

- helpers/crpHelper/crp.helper.go
- swagger/swagger.json
Se integra cambio en el servicio para listar solicitudes de CRP
> servicio certificado RP

- controllers/fuente_financiamiento_apropiacion.go
- helpers/fuenteApropiacionHelper/fuente_apropiacion.helper.go
- managers/movimientoManager/movimiento.manager.go
- models/fuente_financiamiento.go
- models/fuente_financiamiento_apropiacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
se genera los modelos que permitan los procesos ya generados para modificaciones presupuestales
#39
> #39 se agrega endpoint para modificaciones de fuentes

- helpers/crpHelper/crp.helper.go
https://github.com/udistrital/presupuesto_cliente/issues/161
> agregando afectacion id de cdo en info crp

- controllers/fuente_financiamiento_apropiacion.go
- helpers/fuenteApropiacionHelper/fuente_apropiacion.helper.go
- managers/fuenteManager/fuente.manager.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
se elimina fuente si no esta distribuida en el plan de adquisiciones
[Issue](https://github.com/udistrital/presupuesto_cliente/issues/148)
> valid delete distributed source

- controllers/modificacion_presupuestal.go
- helpers/commonHelper/common.helper.go
- helpers/modificacionPresupuestalHelper/modificacionpresupuestal.helper.go
- managers/documentoPresupuestalManager/documento_presupuestal.manager.go
- models/documento_presupuestal.go
- models/modificacion_presupuestal.go
- models/movimiento.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
[Issue #156](https://github.com/udistrital/presupuesto_cliente/issues/156)
> se agrega servicio de formatepo de datos para tabla detalle mod pres

- controllers/fuente_financiamiento_apropiacion.go
[Issue #128](https://github.com/udistrital/presupuesto_cliente/issues/148)
> modify label error fuente distribuida

- controllers/modificacion_presupuestal.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
se agrega parametro para tipo de modificacion
[Issue](https://github.com/udistrital/presupuesto_cliente/issues/128)
> get mod by type param

- helpers/fuenteApropiacionHelper/fuente_apropiacion.helper.go
- models/fuente_financiamiento_apropiacion.go
- swagger/swagger.json
se modifica helper de fuentes para que encapsule los movimientos a los rubros relacionados
> modify model and helper

- interceptor.go
- main.go
- swagger/swagger.json
[Issue #47](https://github.com/udistrital/financiera_documentacion/issues/47)
> Dev -> Test Dev 19 Se agrega auditoria

- helpers/crpHelper/crp.helper.go
- models/crp.go
https://github.com/udistrital/presupuesto_cliente/issues/161
https://github.com/udistrital/presupuesto_cliente/issues/278
> Estados CRP

- helpers/crpHelper/crp.helper.go
> Dev -> Test Dec 23 import crp model

- controllers/vigencia.go
- helpers/crpHelper/crp.helper.go
- helpers/vigenciaHelper/vigencia.helper.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
[Issue #245](udistrital/presupuesto_cliente#245)
> Dev -> Test Dec 26 Ajuste endpoint cierre vigencia

- README.md
https://github.com/udistrital/presupuesto_cliente/issues/468
> doc: release/0.1.0

- helpers/necesidadHelper/movimientopresu.go
https://github.com/udistrital/necesidades_cliente/issues/303
> feat: ajuste para no pasar valores negativos

- controllers/cdp.go
Resuelve: udistrital/presupuesto_cliente#469
> refactor: Ajuste tipos de dato para aprobacion

- helpers/crud/consecutivo/consecutivo.go
- helpers/movimientoHelper/movimiento.helper.go
- helpers/necesidadHelper/movimientopresu.go
https://github.com/udistrital/necesidades_cliente/issues/318
> fix: generar consecutivo

- helpers/necesidadHelper/movimientopresu.go
https://github.com/udistrital/necesidades_cliente/issues/318
> fix: Ajuste para ignorar monto parcial 0

- helpers/crud/consecutivo/consecutivo.go
- helpers/necesidadHelper/movimientopresu.go
https://github.com/udistrital/necesidades_cliente/issues/318
> Develop to Release

- helpers/necesidadHelper/movimientopresu.go
https://github.com/udistrital/financiera_documentacion/issues/444
> fix: Envio de datos en los detalles de movimientos

- README.md
- helpers/necesidadHelper/movimientopresu.go
https://github.com/udistrital/necesidades_cliente/issues/306
> docs: README release
